// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.ray.user.grpc;

public interface AuthenticationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Authentication)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error = 1;</code>
   */
  java.lang.String getError();
  /**
   * <code>string error = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string refreshToken = 3;</code>
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refreshToken = 3;</code>
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();

  /**
   * <code>.user.Date refreshTokenExpiry = 4;</code>
   */
  boolean hasRefreshTokenExpiry();
  /**
   * <code>.user.Date refreshTokenExpiry = 4;</code>
   */
  com.ray.user.grpc.Date getRefreshTokenExpiry();
  /**
   * <code>.user.Date refreshTokenExpiry = 4;</code>
   */
  com.ray.user.grpc.DateOrBuilder getRefreshTokenExpiryOrBuilder();
}
