// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.ray.user.grpc;

public interface UserRoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserRole)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role = 2;</code>
   */
  java.lang.String getRole();
  /**
   * <code>string role = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
