// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: email.proto

package com.ray.email.grpc;

public interface EmailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:email.EmailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.email.MailStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.email.MailStatus status = 1;</code>
   */
  com.ray.email.grpc.MailStatus getStatus();
}
