// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicle.proto

package com.ray.vehicle.grpc;

/**
 * Protobuf type {@code vehicle.Availability}
 */
public  final class Availability extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vehicle.Availability)
    AvailabilityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Availability.newBuilder() to construct.
  private Availability(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Availability() {
    isAvailableForRent_ = false;
    isAvailableForRideHailing_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Availability(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isAvailableForRent_ = input.readBool();
            break;
          }
          case 16: {

            isAvailableForRideHailing_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ray.vehicle.grpc.VehicleServiceImpl.internal_static_vehicle_Availability_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ray.vehicle.grpc.VehicleServiceImpl.internal_static_vehicle_Availability_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ray.vehicle.grpc.Availability.class, com.ray.vehicle.grpc.Availability.Builder.class);
  }

  public static final int IS_AVAILABLE_FOR_RENT_FIELD_NUMBER = 1;
  private boolean isAvailableForRent_;
  /**
   * <code>bool is_available_for_rent = 1;</code>
   */
  public boolean getIsAvailableForRent() {
    return isAvailableForRent_;
  }

  public static final int IS_AVAILABLE_FOR_RIDE_HAILING_FIELD_NUMBER = 2;
  private boolean isAvailableForRideHailing_;
  /**
   * <code>bool is_available_for_ride_hailing = 2;</code>
   */
  public boolean getIsAvailableForRideHailing() {
    return isAvailableForRideHailing_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isAvailableForRent_ != false) {
      output.writeBool(1, isAvailableForRent_);
    }
    if (isAvailableForRideHailing_ != false) {
      output.writeBool(2, isAvailableForRideHailing_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isAvailableForRent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isAvailableForRent_);
    }
    if (isAvailableForRideHailing_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isAvailableForRideHailing_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ray.vehicle.grpc.Availability)) {
      return super.equals(obj);
    }
    com.ray.vehicle.grpc.Availability other = (com.ray.vehicle.grpc.Availability) obj;

    boolean result = true;
    result = result && (getIsAvailableForRent()
        == other.getIsAvailableForRent());
    result = result && (getIsAvailableForRideHailing()
        == other.getIsAvailableForRideHailing());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_AVAILABLE_FOR_RENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAvailableForRent());
    hash = (37 * hash) + IS_AVAILABLE_FOR_RIDE_HAILING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAvailableForRideHailing());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ray.vehicle.grpc.Availability parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ray.vehicle.grpc.Availability parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ray.vehicle.grpc.Availability parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ray.vehicle.grpc.Availability parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ray.vehicle.grpc.Availability prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vehicle.Availability}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vehicle.Availability)
      com.ray.vehicle.grpc.AvailabilityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ray.vehicle.grpc.VehicleServiceImpl.internal_static_vehicle_Availability_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ray.vehicle.grpc.VehicleServiceImpl.internal_static_vehicle_Availability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ray.vehicle.grpc.Availability.class, com.ray.vehicle.grpc.Availability.Builder.class);
    }

    // Construct using com.ray.vehicle.grpc.Availability.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isAvailableForRent_ = false;

      isAvailableForRideHailing_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ray.vehicle.grpc.VehicleServiceImpl.internal_static_vehicle_Availability_descriptor;
    }

    @java.lang.Override
    public com.ray.vehicle.grpc.Availability getDefaultInstanceForType() {
      return com.ray.vehicle.grpc.Availability.getDefaultInstance();
    }

    @java.lang.Override
    public com.ray.vehicle.grpc.Availability build() {
      com.ray.vehicle.grpc.Availability result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ray.vehicle.grpc.Availability buildPartial() {
      com.ray.vehicle.grpc.Availability result = new com.ray.vehicle.grpc.Availability(this);
      result.isAvailableForRent_ = isAvailableForRent_;
      result.isAvailableForRideHailing_ = isAvailableForRideHailing_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ray.vehicle.grpc.Availability) {
        return mergeFrom((com.ray.vehicle.grpc.Availability)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ray.vehicle.grpc.Availability other) {
      if (other == com.ray.vehicle.grpc.Availability.getDefaultInstance()) return this;
      if (other.getIsAvailableForRent() != false) {
        setIsAvailableForRent(other.getIsAvailableForRent());
      }
      if (other.getIsAvailableForRideHailing() != false) {
        setIsAvailableForRideHailing(other.getIsAvailableForRideHailing());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ray.vehicle.grpc.Availability parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ray.vehicle.grpc.Availability) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isAvailableForRent_ ;
    /**
     * <code>bool is_available_for_rent = 1;</code>
     */
    public boolean getIsAvailableForRent() {
      return isAvailableForRent_;
    }
    /**
     * <code>bool is_available_for_rent = 1;</code>
     */
    public Builder setIsAvailableForRent(boolean value) {
      
      isAvailableForRent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_available_for_rent = 1;</code>
     */
    public Builder clearIsAvailableForRent() {
      
      isAvailableForRent_ = false;
      onChanged();
      return this;
    }

    private boolean isAvailableForRideHailing_ ;
    /**
     * <code>bool is_available_for_ride_hailing = 2;</code>
     */
    public boolean getIsAvailableForRideHailing() {
      return isAvailableForRideHailing_;
    }
    /**
     * <code>bool is_available_for_ride_hailing = 2;</code>
     */
    public Builder setIsAvailableForRideHailing(boolean value) {
      
      isAvailableForRideHailing_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_available_for_ride_hailing = 2;</code>
     */
    public Builder clearIsAvailableForRideHailing() {
      
      isAvailableForRideHailing_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vehicle.Availability)
  }

  // @@protoc_insertion_point(class_scope:vehicle.Availability)
  private static final com.ray.vehicle.grpc.Availability DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ray.vehicle.grpc.Availability();
  }

  public static com.ray.vehicle.grpc.Availability getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Availability>
      PARSER = new com.google.protobuf.AbstractParser<Availability>() {
    @java.lang.Override
    public Availability parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Availability(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Availability> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Availability> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ray.vehicle.grpc.Availability getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

