// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.ray.vehicle.grpc;

public interface DateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Date)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   */
  int getDay();
}
