// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicle.proto

package com.ray.vehicle.grpc;

public final class VehicleServiceImpl {
  private VehicleServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vehicle_Vehicle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vehicle_Vehicle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vehicle_Availability_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vehicle_Availability_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vehicle_VehicleCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vehicle_VehicleCategory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vehicle_VehicleFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vehicle_VehicleFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vehicle_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vehicle_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rvehicle.proto\022\007vehicle\"\247\003\n\007Vehicle\022\014\n\004" +
      "make\030\001 \001(\t\022\r\n\005model\030\002 \001(\t\022\014\n\004year\030\003 \001(\005\022" +
      "\r\n\005color\030\004 \001(\t\022\017\n\007mileage\030\005 \001(\005\022\022\n\nrent_" +
      "price\030\006 \001(\001\022\023\n\013engine_type\030\007 \001(\t\022\021\n\tfuel" +
      "_type\030\010 \001(\t\022\024\n\014transmission\030\t \001(\t\022\022\n\nrid" +
      "e_price\030\n \001(\001\022\020\n\010fileName\030\013 \001(\t\022\r\n\005image" +
      "\030\014 \001(\014\022\022\n\nowner_name\030\r \001(\t\022\023\n\013owner_emai" +
      "l\030\016 \001(\t\022\035\n\025is_available_for_rent\030\017 \001(\010\022%" +
      "\n\035is_available_for_ride_hailing\030\020 \001(\010\022*\n" +
      "\010category\030\021 \001(\0132\030.vehicle.VehicleCategor" +
      "y\022\n\n\002id\030\022 \001(\005\022\020\n\010plate_no\030\023 \001(\t\022\021\n\tbody_" +
      "type\030\024 \001(\t\"T\n\014Availability\022\035\n\025is_availab" +
      "le_for_rent\030\001 \001(\010\022%\n\035is_available_for_ri" +
      "de_hailing\030\002 \001(\010\"\205\001\n\017VehicleCategory\022\014\n\004" +
      "name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\020\n\010fileN" +
      "ame\030\003 \001(\t\022\r\n\005image\030\004 \001(\014\022\n\n\002id\030\022 \001(\005\022\"\n\010" +
      "vehicles\030\005 \003(\0132\020.vehicle.Vehicle\"\017\n\rVehi" +
      "cleFilter\"\007\n\005Empty2\257\003\n\016VehicleService\0222\n" +
      "\naddVehicle\022\020.vehicle.Vehicle\032\020.vehicle." +
      "Vehicle\"\000\022;\n\013getVehicles\022\026.vehicle.Vehic" +
      "leFilter\032\020.vehicle.Vehicle\"\0000\001\022.\n\006update" +
      "\022\020.vehicle.Vehicle\032\020.vehicle.Vehicle\"\000\022G" +
      "\n\013addCategory\022\030.vehicle.VehicleCategory\032" +
      "\030.vehicle.VehicleCategory\"\000(\0010\001\022=\n\rgetCa" +
      "tegories\022\016.vehicle.Empty\032\030.vehicle.Vehic" +
      "leCategory\"\0000\001\022@\n\023confirmAvailability\022\020." +
      "vehicle.Vehicle\032\025.vehicle.Availability\"\000" +
      "\0222\n\ngetVehicle\022\020.vehicle.Vehicle\032\020.vehic" +
      "le.Vehicle\"\000B,\n\024com.ray.vehicle.grpcB\022Ve" +
      "hicleServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vehicle_Vehicle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vehicle_Vehicle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vehicle_Vehicle_descriptor,
        new java.lang.String[] { "Make", "Model", "Year", "Color", "Mileage", "RentPrice", "EngineType", "FuelType", "Transmission", "RidePrice", "FileName", "Image", "OwnerName", "OwnerEmail", "IsAvailableForRent", "IsAvailableForRideHailing", "Category", "Id", "PlateNo", "BodyType", });
    internal_static_vehicle_Availability_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vehicle_Availability_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vehicle_Availability_descriptor,
        new java.lang.String[] { "IsAvailableForRent", "IsAvailableForRideHailing", });
    internal_static_vehicle_VehicleCategory_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_vehicle_VehicleCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vehicle_VehicleCategory_descriptor,
        new java.lang.String[] { "Name", "Description", "FileName", "Image", "Id", "Vehicles", });
    internal_static_vehicle_VehicleFilter_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_vehicle_VehicleFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vehicle_VehicleFilter_descriptor,
        new java.lang.String[] { });
    internal_static_vehicle_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_vehicle_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vehicle_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
