// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicle.proto

package com.ray.vehicle.grpc;

public interface VehicleCategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vehicle.VehicleCategory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string fileName = 3;</code>
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>bytes image = 4;</code>
   */
  com.google.protobuf.ByteString getImage();

  /**
   * <code>int32 id = 18;</code>
   */
  int getId();

  /**
   * <code>repeated .vehicle.Vehicle vehicles = 5;</code>
   */
  java.util.List<com.ray.vehicle.grpc.Vehicle> 
      getVehiclesList();
  /**
   * <code>repeated .vehicle.Vehicle vehicles = 5;</code>
   */
  com.ray.vehicle.grpc.Vehicle getVehicles(int index);
  /**
   * <code>repeated .vehicle.Vehicle vehicles = 5;</code>
   */
  int getVehiclesCount();
  /**
   * <code>repeated .vehicle.Vehicle vehicles = 5;</code>
   */
  java.util.List<? extends com.ray.vehicle.grpc.VehicleOrBuilder> 
      getVehiclesOrBuilderList();
  /**
   * <code>repeated .vehicle.Vehicle vehicles = 5;</code>
   */
  com.ray.vehicle.grpc.VehicleOrBuilder getVehiclesOrBuilder(
      int index);
}
