// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicle.proto

package com.ray.app.grpc;

public interface CategoryFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vehicle.CategoryFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 2;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 2;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>int32 limit = 4;</code>
   */
  int getLimit();
}
