// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package com.ray.app.grpc;

public interface DateTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedule.DateTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   */
  int getDay();

  /**
   * <code>int32 hour = 4;</code>
   */
  int getHour();

  /**
   * <code>int32 minute = 5;</code>
   */
  int getMinute();

  /**
   * <code>int32 second = 6;</code>
   */
  int getSecond();
}
