// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicle.proto

package com.ray.app.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vehicle.Empty)
    com.google.protobuf.MessageOrBuilder {
}
