// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package com.ray.app.grpc;

public interface ReservationFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedule.ReservationFilter)
    com.google.protobuf.MessageOrBuilder {
}
