// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package com.ray.app.grpc;

/**
 * Protobuf type {@code schedule.Reservation}
 */
public  final class Reservation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:schedule.Reservation)
    ReservationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Reservation.newBuilder() to construct.
  private Reservation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Reservation() {
    id_ = 0;
    vehicleId_ = 0;
    clientEmail_ = "";
    clientName_ = "";
    type_ = "";
    pickupAddress_ = "";
    destinationAddress_ = "";
    dropOffAddress_ = "";
    pickupLatitude_ = 0D;
    pickupLongitude_ = 0D;
    dropOffLatitude_ = 0D;
    dropOffLongitude_ = 0D;
    destinationLatitude_ = 0D;
    destinationLongitude_ = 0D;
    status_ = "";
    rating_ = 0D;
    vehiclePlateNo_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Reservation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            vehicleId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            clientEmail_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            clientName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            pickupAddress_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationAddress_ = s;
            break;
          }
          case 66: {
            com.ray.app.grpc.DateTime.Builder subBuilder = null;
            if (pickupTime_ != null) {
              subBuilder = pickupTime_.toBuilder();
            }
            pickupTime_ = input.readMessage(com.ray.app.grpc.DateTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pickupTime_);
              pickupTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.ray.app.grpc.DateTime.Builder subBuilder = null;
            if (dropOffTime_ != null) {
              subBuilder = dropOffTime_.toBuilder();
            }
            dropOffTime_ = input.readMessage(com.ray.app.grpc.DateTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dropOffTime_);
              dropOffTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            dropOffAddress_ = s;
            break;
          }
          case 90: {
            com.ray.app.grpc.DateTime.Builder subBuilder = null;
            if (expectedEndTime_ != null) {
              subBuilder = expectedEndTime_.toBuilder();
            }
            expectedEndTime_ = input.readMessage(com.ray.app.grpc.DateTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expectedEndTime_);
              expectedEndTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 97: {

            pickupLatitude_ = input.readDouble();
            break;
          }
          case 105: {

            pickupLongitude_ = input.readDouble();
            break;
          }
          case 113: {

            dropOffLatitude_ = input.readDouble();
            break;
          }
          case 121: {

            dropOffLongitude_ = input.readDouble();
            break;
          }
          case 129: {

            destinationLatitude_ = input.readDouble();
            break;
          }
          case 137: {

            destinationLongitude_ = input.readDouble();
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 153: {

            rating_ = input.readDouble();
            break;
          }
          case 162: {
            java.lang.String s = input.readStringRequireUtf8();

            vehiclePlateNo_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ray.app.grpc.ScheduleServiceImpl.internal_static_schedule_Reservation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ray.app.grpc.ScheduleServiceImpl.internal_static_schedule_Reservation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ray.app.grpc.Reservation.class, com.ray.app.grpc.Reservation.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int VEHICLE_ID_FIELD_NUMBER = 2;
  private int vehicleId_;
  /**
   * <code>int32 vehicle_id = 2;</code>
   */
  public int getVehicleId() {
    return vehicleId_;
  }

  public static final int CLIENT_EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object clientEmail_;
  /**
   * <code>string client_email = 3;</code>
   */
  public java.lang.String getClientEmail() {
    java.lang.Object ref = clientEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string client_email = 3;</code>
   */
  public com.google.protobuf.ByteString
      getClientEmailBytes() {
    java.lang.Object ref = clientEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object clientName_;
  /**
   * <code>string client_name = 4;</code>
   */
  public java.lang.String getClientName() {
    java.lang.Object ref = clientName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientName_ = s;
      return s;
    }
  }
  /**
   * <code>string client_name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getClientNameBytes() {
    java.lang.Object ref = clientName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 5;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICKUP_ADDRESS_FIELD_NUMBER = 6;
  private volatile java.lang.Object pickupAddress_;
  /**
   * <code>string pickup_address = 6;</code>
   */
  public java.lang.String getPickupAddress() {
    java.lang.Object ref = pickupAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pickupAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string pickup_address = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPickupAddressBytes() {
    java.lang.Object ref = pickupAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pickupAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_ADDRESS_FIELD_NUMBER = 7;
  private volatile java.lang.Object destinationAddress_;
  /**
   * <code>string destination_address = 7;</code>
   */
  public java.lang.String getDestinationAddress() {
    java.lang.Object ref = destinationAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_address = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationAddressBytes() {
    java.lang.Object ref = destinationAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICKUP_TIME_FIELD_NUMBER = 8;
  private com.ray.app.grpc.DateTime pickupTime_;
  /**
   * <code>.schedule.DateTime pickup_time = 8;</code>
   */
  public boolean hasPickupTime() {
    return pickupTime_ != null;
  }
  /**
   * <code>.schedule.DateTime pickup_time = 8;</code>
   */
  public com.ray.app.grpc.DateTime getPickupTime() {
    return pickupTime_ == null ? com.ray.app.grpc.DateTime.getDefaultInstance() : pickupTime_;
  }
  /**
   * <code>.schedule.DateTime pickup_time = 8;</code>
   */
  public com.ray.app.grpc.DateTimeOrBuilder getPickupTimeOrBuilder() {
    return getPickupTime();
  }

  public static final int DROP_OFF_TIME_FIELD_NUMBER = 9;
  private com.ray.app.grpc.DateTime dropOffTime_;
  /**
   * <code>.schedule.DateTime drop_off_time = 9;</code>
   */
  public boolean hasDropOffTime() {
    return dropOffTime_ != null;
  }
  /**
   * <code>.schedule.DateTime drop_off_time = 9;</code>
   */
  public com.ray.app.grpc.DateTime getDropOffTime() {
    return dropOffTime_ == null ? com.ray.app.grpc.DateTime.getDefaultInstance() : dropOffTime_;
  }
  /**
   * <code>.schedule.DateTime drop_off_time = 9;</code>
   */
  public com.ray.app.grpc.DateTimeOrBuilder getDropOffTimeOrBuilder() {
    return getDropOffTime();
  }

  public static final int DROP_OFF_ADDRESS_FIELD_NUMBER = 10;
  private volatile java.lang.Object dropOffAddress_;
  /**
   * <code>string drop_off_address = 10;</code>
   */
  public java.lang.String getDropOffAddress() {
    java.lang.Object ref = dropOffAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dropOffAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string drop_off_address = 10;</code>
   */
  public com.google.protobuf.ByteString
      getDropOffAddressBytes() {
    java.lang.Object ref = dropOffAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dropOffAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPECTED_END_TIME_FIELD_NUMBER = 11;
  private com.ray.app.grpc.DateTime expectedEndTime_;
  /**
   * <code>.schedule.DateTime expected_end_time = 11;</code>
   */
  public boolean hasExpectedEndTime() {
    return expectedEndTime_ != null;
  }
  /**
   * <code>.schedule.DateTime expected_end_time = 11;</code>
   */
  public com.ray.app.grpc.DateTime getExpectedEndTime() {
    return expectedEndTime_ == null ? com.ray.app.grpc.DateTime.getDefaultInstance() : expectedEndTime_;
  }
  /**
   * <code>.schedule.DateTime expected_end_time = 11;</code>
   */
  public com.ray.app.grpc.DateTimeOrBuilder getExpectedEndTimeOrBuilder() {
    return getExpectedEndTime();
  }

  public static final int PICKUP_LATITUDE_FIELD_NUMBER = 12;
  private double pickupLatitude_;
  /**
   * <code>double pickup_latitude = 12;</code>
   */
  public double getPickupLatitude() {
    return pickupLatitude_;
  }

  public static final int PICKUP_LONGITUDE_FIELD_NUMBER = 13;
  private double pickupLongitude_;
  /**
   * <code>double pickup_longitude = 13;</code>
   */
  public double getPickupLongitude() {
    return pickupLongitude_;
  }

  public static final int DROP_OFF_LATITUDE_FIELD_NUMBER = 14;
  private double dropOffLatitude_;
  /**
   * <code>double drop_off_latitude = 14;</code>
   */
  public double getDropOffLatitude() {
    return dropOffLatitude_;
  }

  public static final int DROP_OFF_LONGITUDE_FIELD_NUMBER = 15;
  private double dropOffLongitude_;
  /**
   * <code>double drop_off_longitude = 15;</code>
   */
  public double getDropOffLongitude() {
    return dropOffLongitude_;
  }

  public static final int DESTINATION_LATITUDE_FIELD_NUMBER = 16;
  private double destinationLatitude_;
  /**
   * <code>double destination_latitude = 16;</code>
   */
  public double getDestinationLatitude() {
    return destinationLatitude_;
  }

  public static final int DESTINATION_LONGITUDE_FIELD_NUMBER = 17;
  private double destinationLongitude_;
  /**
   * <code>double destination_longitude = 17;</code>
   */
  public double getDestinationLongitude() {
    return destinationLongitude_;
  }

  public static final int STATUS_FIELD_NUMBER = 18;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 18;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 18;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATING_FIELD_NUMBER = 19;
  private double rating_;
  /**
   * <code>double rating = 19;</code>
   */
  public double getRating() {
    return rating_;
  }

  public static final int VEHICLE_PLATE_NO_FIELD_NUMBER = 20;
  private volatile java.lang.Object vehiclePlateNo_;
  /**
   * <code>string vehicle_plate_no = 20;</code>
   */
  public java.lang.String getVehiclePlateNo() {
    java.lang.Object ref = vehiclePlateNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vehiclePlateNo_ = s;
      return s;
    }
  }
  /**
   * <code>string vehicle_plate_no = 20;</code>
   */
  public com.google.protobuf.ByteString
      getVehiclePlateNoBytes() {
    java.lang.Object ref = vehiclePlateNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vehiclePlateNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (vehicleId_ != 0) {
      output.writeInt32(2, vehicleId_);
    }
    if (!getClientEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientEmail_);
    }
    if (!getClientNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientName_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, type_);
    }
    if (!getPickupAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, pickupAddress_);
    }
    if (!getDestinationAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, destinationAddress_);
    }
    if (pickupTime_ != null) {
      output.writeMessage(8, getPickupTime());
    }
    if (dropOffTime_ != null) {
      output.writeMessage(9, getDropOffTime());
    }
    if (!getDropOffAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dropOffAddress_);
    }
    if (expectedEndTime_ != null) {
      output.writeMessage(11, getExpectedEndTime());
    }
    if (pickupLatitude_ != 0D) {
      output.writeDouble(12, pickupLatitude_);
    }
    if (pickupLongitude_ != 0D) {
      output.writeDouble(13, pickupLongitude_);
    }
    if (dropOffLatitude_ != 0D) {
      output.writeDouble(14, dropOffLatitude_);
    }
    if (dropOffLongitude_ != 0D) {
      output.writeDouble(15, dropOffLongitude_);
    }
    if (destinationLatitude_ != 0D) {
      output.writeDouble(16, destinationLatitude_);
    }
    if (destinationLongitude_ != 0D) {
      output.writeDouble(17, destinationLongitude_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, status_);
    }
    if (rating_ != 0D) {
      output.writeDouble(19, rating_);
    }
    if (!getVehiclePlateNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, vehiclePlateNo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (vehicleId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, vehicleId_);
    }
    if (!getClientEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientEmail_);
    }
    if (!getClientNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientName_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, type_);
    }
    if (!getPickupAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, pickupAddress_);
    }
    if (!getDestinationAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, destinationAddress_);
    }
    if (pickupTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getPickupTime());
    }
    if (dropOffTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getDropOffTime());
    }
    if (!getDropOffAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dropOffAddress_);
    }
    if (expectedEndTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getExpectedEndTime());
    }
    if (pickupLatitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, pickupLatitude_);
    }
    if (pickupLongitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(13, pickupLongitude_);
    }
    if (dropOffLatitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(14, dropOffLatitude_);
    }
    if (dropOffLongitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(15, dropOffLongitude_);
    }
    if (destinationLatitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(16, destinationLatitude_);
    }
    if (destinationLongitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(17, destinationLongitude_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, status_);
    }
    if (rating_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(19, rating_);
    }
    if (!getVehiclePlateNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, vehiclePlateNo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ray.app.grpc.Reservation)) {
      return super.equals(obj);
    }
    com.ray.app.grpc.Reservation other = (com.ray.app.grpc.Reservation) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getVehicleId()
        == other.getVehicleId());
    result = result && getClientEmail()
        .equals(other.getClientEmail());
    result = result && getClientName()
        .equals(other.getClientName());
    result = result && getType()
        .equals(other.getType());
    result = result && getPickupAddress()
        .equals(other.getPickupAddress());
    result = result && getDestinationAddress()
        .equals(other.getDestinationAddress());
    result = result && (hasPickupTime() == other.hasPickupTime());
    if (hasPickupTime()) {
      result = result && getPickupTime()
          .equals(other.getPickupTime());
    }
    result = result && (hasDropOffTime() == other.hasDropOffTime());
    if (hasDropOffTime()) {
      result = result && getDropOffTime()
          .equals(other.getDropOffTime());
    }
    result = result && getDropOffAddress()
        .equals(other.getDropOffAddress());
    result = result && (hasExpectedEndTime() == other.hasExpectedEndTime());
    if (hasExpectedEndTime()) {
      result = result && getExpectedEndTime()
          .equals(other.getExpectedEndTime());
    }
    result = result && (
        java.lang.Double.doubleToLongBits(getPickupLatitude())
        == java.lang.Double.doubleToLongBits(
            other.getPickupLatitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getPickupLongitude())
        == java.lang.Double.doubleToLongBits(
            other.getPickupLongitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getDropOffLatitude())
        == java.lang.Double.doubleToLongBits(
            other.getDropOffLatitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getDropOffLongitude())
        == java.lang.Double.doubleToLongBits(
            other.getDropOffLongitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getDestinationLatitude())
        == java.lang.Double.doubleToLongBits(
            other.getDestinationLatitude()));
    result = result && (
        java.lang.Double.doubleToLongBits(getDestinationLongitude())
        == java.lang.Double.doubleToLongBits(
            other.getDestinationLongitude()));
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && (
        java.lang.Double.doubleToLongBits(getRating())
        == java.lang.Double.doubleToLongBits(
            other.getRating()));
    result = result && getVehiclePlateNo()
        .equals(other.getVehiclePlateNo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + VEHICLE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVehicleId();
    hash = (37 * hash) + CLIENT_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getClientEmail().hashCode();
    hash = (37 * hash) + CLIENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + PICKUP_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getPickupAddress().hashCode();
    hash = (37 * hash) + DESTINATION_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationAddress().hashCode();
    if (hasPickupTime()) {
      hash = (37 * hash) + PICKUP_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getPickupTime().hashCode();
    }
    if (hasDropOffTime()) {
      hash = (37 * hash) + DROP_OFF_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getDropOffTime().hashCode();
    }
    hash = (37 * hash) + DROP_OFF_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getDropOffAddress().hashCode();
    if (hasExpectedEndTime()) {
      hash = (37 * hash) + EXPECTED_END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getExpectedEndTime().hashCode();
    }
    hash = (37 * hash) + PICKUP_LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPickupLatitude()));
    hash = (37 * hash) + PICKUP_LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPickupLongitude()));
    hash = (37 * hash) + DROP_OFF_LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDropOffLatitude()));
    hash = (37 * hash) + DROP_OFF_LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDropOffLongitude()));
    hash = (37 * hash) + DESTINATION_LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDestinationLatitude()));
    hash = (37 * hash) + DESTINATION_LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDestinationLongitude()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRating()));
    hash = (37 * hash) + VEHICLE_PLATE_NO_FIELD_NUMBER;
    hash = (53 * hash) + getVehiclePlateNo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ray.app.grpc.Reservation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.app.grpc.Reservation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.app.grpc.Reservation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.app.grpc.Reservation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.app.grpc.Reservation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.app.grpc.Reservation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.app.grpc.Reservation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ray.app.grpc.Reservation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ray.app.grpc.Reservation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ray.app.grpc.Reservation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ray.app.grpc.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ray.app.grpc.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ray.app.grpc.Reservation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code schedule.Reservation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:schedule.Reservation)
      com.ray.app.grpc.ReservationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ray.app.grpc.ScheduleServiceImpl.internal_static_schedule_Reservation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ray.app.grpc.ScheduleServiceImpl.internal_static_schedule_Reservation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ray.app.grpc.Reservation.class, com.ray.app.grpc.Reservation.Builder.class);
    }

    // Construct using com.ray.app.grpc.Reservation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      vehicleId_ = 0;

      clientEmail_ = "";

      clientName_ = "";

      type_ = "";

      pickupAddress_ = "";

      destinationAddress_ = "";

      if (pickupTimeBuilder_ == null) {
        pickupTime_ = null;
      } else {
        pickupTime_ = null;
        pickupTimeBuilder_ = null;
      }
      if (dropOffTimeBuilder_ == null) {
        dropOffTime_ = null;
      } else {
        dropOffTime_ = null;
        dropOffTimeBuilder_ = null;
      }
      dropOffAddress_ = "";

      if (expectedEndTimeBuilder_ == null) {
        expectedEndTime_ = null;
      } else {
        expectedEndTime_ = null;
        expectedEndTimeBuilder_ = null;
      }
      pickupLatitude_ = 0D;

      pickupLongitude_ = 0D;

      dropOffLatitude_ = 0D;

      dropOffLongitude_ = 0D;

      destinationLatitude_ = 0D;

      destinationLongitude_ = 0D;

      status_ = "";

      rating_ = 0D;

      vehiclePlateNo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ray.app.grpc.ScheduleServiceImpl.internal_static_schedule_Reservation_descriptor;
    }

    @java.lang.Override
    public com.ray.app.grpc.Reservation getDefaultInstanceForType() {
      return com.ray.app.grpc.Reservation.getDefaultInstance();
    }

    @java.lang.Override
    public com.ray.app.grpc.Reservation build() {
      com.ray.app.grpc.Reservation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ray.app.grpc.Reservation buildPartial() {
      com.ray.app.grpc.Reservation result = new com.ray.app.grpc.Reservation(this);
      result.id_ = id_;
      result.vehicleId_ = vehicleId_;
      result.clientEmail_ = clientEmail_;
      result.clientName_ = clientName_;
      result.type_ = type_;
      result.pickupAddress_ = pickupAddress_;
      result.destinationAddress_ = destinationAddress_;
      if (pickupTimeBuilder_ == null) {
        result.pickupTime_ = pickupTime_;
      } else {
        result.pickupTime_ = pickupTimeBuilder_.build();
      }
      if (dropOffTimeBuilder_ == null) {
        result.dropOffTime_ = dropOffTime_;
      } else {
        result.dropOffTime_ = dropOffTimeBuilder_.build();
      }
      result.dropOffAddress_ = dropOffAddress_;
      if (expectedEndTimeBuilder_ == null) {
        result.expectedEndTime_ = expectedEndTime_;
      } else {
        result.expectedEndTime_ = expectedEndTimeBuilder_.build();
      }
      result.pickupLatitude_ = pickupLatitude_;
      result.pickupLongitude_ = pickupLongitude_;
      result.dropOffLatitude_ = dropOffLatitude_;
      result.dropOffLongitude_ = dropOffLongitude_;
      result.destinationLatitude_ = destinationLatitude_;
      result.destinationLongitude_ = destinationLongitude_;
      result.status_ = status_;
      result.rating_ = rating_;
      result.vehiclePlateNo_ = vehiclePlateNo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ray.app.grpc.Reservation) {
        return mergeFrom((com.ray.app.grpc.Reservation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ray.app.grpc.Reservation other) {
      if (other == com.ray.app.grpc.Reservation.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getVehicleId() != 0) {
        setVehicleId(other.getVehicleId());
      }
      if (!other.getClientEmail().isEmpty()) {
        clientEmail_ = other.clientEmail_;
        onChanged();
      }
      if (!other.getClientName().isEmpty()) {
        clientName_ = other.clientName_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getPickupAddress().isEmpty()) {
        pickupAddress_ = other.pickupAddress_;
        onChanged();
      }
      if (!other.getDestinationAddress().isEmpty()) {
        destinationAddress_ = other.destinationAddress_;
        onChanged();
      }
      if (other.hasPickupTime()) {
        mergePickupTime(other.getPickupTime());
      }
      if (other.hasDropOffTime()) {
        mergeDropOffTime(other.getDropOffTime());
      }
      if (!other.getDropOffAddress().isEmpty()) {
        dropOffAddress_ = other.dropOffAddress_;
        onChanged();
      }
      if (other.hasExpectedEndTime()) {
        mergeExpectedEndTime(other.getExpectedEndTime());
      }
      if (other.getPickupLatitude() != 0D) {
        setPickupLatitude(other.getPickupLatitude());
      }
      if (other.getPickupLongitude() != 0D) {
        setPickupLongitude(other.getPickupLongitude());
      }
      if (other.getDropOffLatitude() != 0D) {
        setDropOffLatitude(other.getDropOffLatitude());
      }
      if (other.getDropOffLongitude() != 0D) {
        setDropOffLongitude(other.getDropOffLongitude());
      }
      if (other.getDestinationLatitude() != 0D) {
        setDestinationLatitude(other.getDestinationLatitude());
      }
      if (other.getDestinationLongitude() != 0D) {
        setDestinationLongitude(other.getDestinationLongitude());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getRating() != 0D) {
        setRating(other.getRating());
      }
      if (!other.getVehiclePlateNo().isEmpty()) {
        vehiclePlateNo_ = other.vehiclePlateNo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ray.app.grpc.Reservation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ray.app.grpc.Reservation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int vehicleId_ ;
    /**
     * <code>int32 vehicle_id = 2;</code>
     */
    public int getVehicleId() {
      return vehicleId_;
    }
    /**
     * <code>int32 vehicle_id = 2;</code>
     */
    public Builder setVehicleId(int value) {
      
      vehicleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 vehicle_id = 2;</code>
     */
    public Builder clearVehicleId() {
      
      vehicleId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object clientEmail_ = "";
    /**
     * <code>string client_email = 3;</code>
     */
    public java.lang.String getClientEmail() {
      java.lang.Object ref = clientEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientEmailBytes() {
      java.lang.Object ref = clientEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_email = 3;</code>
     */
    public Builder setClientEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_email = 3;</code>
     */
    public Builder clearClientEmail() {
      
      clientEmail_ = getDefaultInstance().getClientEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string client_email = 3;</code>
     */
    public Builder setClientEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientEmail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientName_ = "";
    /**
     * <code>string client_name = 4;</code>
     */
    public java.lang.String getClientName() {
      java.lang.Object ref = clientName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      java.lang.Object ref = clientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_name = 4;</code>
     */
    public Builder setClientName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_name = 4;</code>
     */
    public Builder clearClientName() {
      
      clientName_ = getDefaultInstance().getClientName();
      onChanged();
      return this;
    }
    /**
     * <code>string client_name = 4;</code>
     */
    public Builder setClientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 5;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 5;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 5;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 5;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pickupAddress_ = "";
    /**
     * <code>string pickup_address = 6;</code>
     */
    public java.lang.String getPickupAddress() {
      java.lang.Object ref = pickupAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pickupAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pickup_address = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPickupAddressBytes() {
      java.lang.Object ref = pickupAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pickupAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pickup_address = 6;</code>
     */
    public Builder setPickupAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pickupAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pickup_address = 6;</code>
     */
    public Builder clearPickupAddress() {
      
      pickupAddress_ = getDefaultInstance().getPickupAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string pickup_address = 6;</code>
     */
    public Builder setPickupAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pickupAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationAddress_ = "";
    /**
     * <code>string destination_address = 7;</code>
     */
    public java.lang.String getDestinationAddress() {
      java.lang.Object ref = destinationAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationAddressBytes() {
      java.lang.Object ref = destinationAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public Builder setDestinationAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public Builder clearDestinationAddress() {
      
      destinationAddress_ = getDefaultInstance().getDestinationAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public Builder setDestinationAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationAddress_ = value;
      onChanged();
      return this;
    }

    private com.ray.app.grpc.DateTime pickupTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder> pickupTimeBuilder_;
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public boolean hasPickupTime() {
      return pickupTimeBuilder_ != null || pickupTime_ != null;
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public com.ray.app.grpc.DateTime getPickupTime() {
      if (pickupTimeBuilder_ == null) {
        return pickupTime_ == null ? com.ray.app.grpc.DateTime.getDefaultInstance() : pickupTime_;
      } else {
        return pickupTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public Builder setPickupTime(com.ray.app.grpc.DateTime value) {
      if (pickupTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pickupTime_ = value;
        onChanged();
      } else {
        pickupTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public Builder setPickupTime(
        com.ray.app.grpc.DateTime.Builder builderForValue) {
      if (pickupTimeBuilder_ == null) {
        pickupTime_ = builderForValue.build();
        onChanged();
      } else {
        pickupTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public Builder mergePickupTime(com.ray.app.grpc.DateTime value) {
      if (pickupTimeBuilder_ == null) {
        if (pickupTime_ != null) {
          pickupTime_ =
            com.ray.app.grpc.DateTime.newBuilder(pickupTime_).mergeFrom(value).buildPartial();
        } else {
          pickupTime_ = value;
        }
        onChanged();
      } else {
        pickupTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public Builder clearPickupTime() {
      if (pickupTimeBuilder_ == null) {
        pickupTime_ = null;
        onChanged();
      } else {
        pickupTime_ = null;
        pickupTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public com.ray.app.grpc.DateTime.Builder getPickupTimeBuilder() {
      
      onChanged();
      return getPickupTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    public com.ray.app.grpc.DateTimeOrBuilder getPickupTimeOrBuilder() {
      if (pickupTimeBuilder_ != null) {
        return pickupTimeBuilder_.getMessageOrBuilder();
      } else {
        return pickupTime_ == null ?
            com.ray.app.grpc.DateTime.getDefaultInstance() : pickupTime_;
      }
    }
    /**
     * <code>.schedule.DateTime pickup_time = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder> 
        getPickupTimeFieldBuilder() {
      if (pickupTimeBuilder_ == null) {
        pickupTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder>(
                getPickupTime(),
                getParentForChildren(),
                isClean());
        pickupTime_ = null;
      }
      return pickupTimeBuilder_;
    }

    private com.ray.app.grpc.DateTime dropOffTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder> dropOffTimeBuilder_;
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public boolean hasDropOffTime() {
      return dropOffTimeBuilder_ != null || dropOffTime_ != null;
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public com.ray.app.grpc.DateTime getDropOffTime() {
      if (dropOffTimeBuilder_ == null) {
        return dropOffTime_ == null ? com.ray.app.grpc.DateTime.getDefaultInstance() : dropOffTime_;
      } else {
        return dropOffTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public Builder setDropOffTime(com.ray.app.grpc.DateTime value) {
      if (dropOffTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dropOffTime_ = value;
        onChanged();
      } else {
        dropOffTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public Builder setDropOffTime(
        com.ray.app.grpc.DateTime.Builder builderForValue) {
      if (dropOffTimeBuilder_ == null) {
        dropOffTime_ = builderForValue.build();
        onChanged();
      } else {
        dropOffTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public Builder mergeDropOffTime(com.ray.app.grpc.DateTime value) {
      if (dropOffTimeBuilder_ == null) {
        if (dropOffTime_ != null) {
          dropOffTime_ =
            com.ray.app.grpc.DateTime.newBuilder(dropOffTime_).mergeFrom(value).buildPartial();
        } else {
          dropOffTime_ = value;
        }
        onChanged();
      } else {
        dropOffTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public Builder clearDropOffTime() {
      if (dropOffTimeBuilder_ == null) {
        dropOffTime_ = null;
        onChanged();
      } else {
        dropOffTime_ = null;
        dropOffTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public com.ray.app.grpc.DateTime.Builder getDropOffTimeBuilder() {
      
      onChanged();
      return getDropOffTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    public com.ray.app.grpc.DateTimeOrBuilder getDropOffTimeOrBuilder() {
      if (dropOffTimeBuilder_ != null) {
        return dropOffTimeBuilder_.getMessageOrBuilder();
      } else {
        return dropOffTime_ == null ?
            com.ray.app.grpc.DateTime.getDefaultInstance() : dropOffTime_;
      }
    }
    /**
     * <code>.schedule.DateTime drop_off_time = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder> 
        getDropOffTimeFieldBuilder() {
      if (dropOffTimeBuilder_ == null) {
        dropOffTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder>(
                getDropOffTime(),
                getParentForChildren(),
                isClean());
        dropOffTime_ = null;
      }
      return dropOffTimeBuilder_;
    }

    private java.lang.Object dropOffAddress_ = "";
    /**
     * <code>string drop_off_address = 10;</code>
     */
    public java.lang.String getDropOffAddress() {
      java.lang.Object ref = dropOffAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dropOffAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string drop_off_address = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDropOffAddressBytes() {
      java.lang.Object ref = dropOffAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dropOffAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string drop_off_address = 10;</code>
     */
    public Builder setDropOffAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dropOffAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string drop_off_address = 10;</code>
     */
    public Builder clearDropOffAddress() {
      
      dropOffAddress_ = getDefaultInstance().getDropOffAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string drop_off_address = 10;</code>
     */
    public Builder setDropOffAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dropOffAddress_ = value;
      onChanged();
      return this;
    }

    private com.ray.app.grpc.DateTime expectedEndTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder> expectedEndTimeBuilder_;
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public boolean hasExpectedEndTime() {
      return expectedEndTimeBuilder_ != null || expectedEndTime_ != null;
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public com.ray.app.grpc.DateTime getExpectedEndTime() {
      if (expectedEndTimeBuilder_ == null) {
        return expectedEndTime_ == null ? com.ray.app.grpc.DateTime.getDefaultInstance() : expectedEndTime_;
      } else {
        return expectedEndTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public Builder setExpectedEndTime(com.ray.app.grpc.DateTime value) {
      if (expectedEndTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expectedEndTime_ = value;
        onChanged();
      } else {
        expectedEndTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public Builder setExpectedEndTime(
        com.ray.app.grpc.DateTime.Builder builderForValue) {
      if (expectedEndTimeBuilder_ == null) {
        expectedEndTime_ = builderForValue.build();
        onChanged();
      } else {
        expectedEndTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public Builder mergeExpectedEndTime(com.ray.app.grpc.DateTime value) {
      if (expectedEndTimeBuilder_ == null) {
        if (expectedEndTime_ != null) {
          expectedEndTime_ =
            com.ray.app.grpc.DateTime.newBuilder(expectedEndTime_).mergeFrom(value).buildPartial();
        } else {
          expectedEndTime_ = value;
        }
        onChanged();
      } else {
        expectedEndTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public Builder clearExpectedEndTime() {
      if (expectedEndTimeBuilder_ == null) {
        expectedEndTime_ = null;
        onChanged();
      } else {
        expectedEndTime_ = null;
        expectedEndTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public com.ray.app.grpc.DateTime.Builder getExpectedEndTimeBuilder() {
      
      onChanged();
      return getExpectedEndTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    public com.ray.app.grpc.DateTimeOrBuilder getExpectedEndTimeOrBuilder() {
      if (expectedEndTimeBuilder_ != null) {
        return expectedEndTimeBuilder_.getMessageOrBuilder();
      } else {
        return expectedEndTime_ == null ?
            com.ray.app.grpc.DateTime.getDefaultInstance() : expectedEndTime_;
      }
    }
    /**
     * <code>.schedule.DateTime expected_end_time = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder> 
        getExpectedEndTimeFieldBuilder() {
      if (expectedEndTimeBuilder_ == null) {
        expectedEndTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ray.app.grpc.DateTime, com.ray.app.grpc.DateTime.Builder, com.ray.app.grpc.DateTimeOrBuilder>(
                getExpectedEndTime(),
                getParentForChildren(),
                isClean());
        expectedEndTime_ = null;
      }
      return expectedEndTimeBuilder_;
    }

    private double pickupLatitude_ ;
    /**
     * <code>double pickup_latitude = 12;</code>
     */
    public double getPickupLatitude() {
      return pickupLatitude_;
    }
    /**
     * <code>double pickup_latitude = 12;</code>
     */
    public Builder setPickupLatitude(double value) {
      
      pickupLatitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double pickup_latitude = 12;</code>
     */
    public Builder clearPickupLatitude() {
      
      pickupLatitude_ = 0D;
      onChanged();
      return this;
    }

    private double pickupLongitude_ ;
    /**
     * <code>double pickup_longitude = 13;</code>
     */
    public double getPickupLongitude() {
      return pickupLongitude_;
    }
    /**
     * <code>double pickup_longitude = 13;</code>
     */
    public Builder setPickupLongitude(double value) {
      
      pickupLongitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double pickup_longitude = 13;</code>
     */
    public Builder clearPickupLongitude() {
      
      pickupLongitude_ = 0D;
      onChanged();
      return this;
    }

    private double dropOffLatitude_ ;
    /**
     * <code>double drop_off_latitude = 14;</code>
     */
    public double getDropOffLatitude() {
      return dropOffLatitude_;
    }
    /**
     * <code>double drop_off_latitude = 14;</code>
     */
    public Builder setDropOffLatitude(double value) {
      
      dropOffLatitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double drop_off_latitude = 14;</code>
     */
    public Builder clearDropOffLatitude() {
      
      dropOffLatitude_ = 0D;
      onChanged();
      return this;
    }

    private double dropOffLongitude_ ;
    /**
     * <code>double drop_off_longitude = 15;</code>
     */
    public double getDropOffLongitude() {
      return dropOffLongitude_;
    }
    /**
     * <code>double drop_off_longitude = 15;</code>
     */
    public Builder setDropOffLongitude(double value) {
      
      dropOffLongitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double drop_off_longitude = 15;</code>
     */
    public Builder clearDropOffLongitude() {
      
      dropOffLongitude_ = 0D;
      onChanged();
      return this;
    }

    private double destinationLatitude_ ;
    /**
     * <code>double destination_latitude = 16;</code>
     */
    public double getDestinationLatitude() {
      return destinationLatitude_;
    }
    /**
     * <code>double destination_latitude = 16;</code>
     */
    public Builder setDestinationLatitude(double value) {
      
      destinationLatitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double destination_latitude = 16;</code>
     */
    public Builder clearDestinationLatitude() {
      
      destinationLatitude_ = 0D;
      onChanged();
      return this;
    }

    private double destinationLongitude_ ;
    /**
     * <code>double destination_longitude = 17;</code>
     */
    public double getDestinationLongitude() {
      return destinationLongitude_;
    }
    /**
     * <code>double destination_longitude = 17;</code>
     */
    public Builder setDestinationLongitude(double value) {
      
      destinationLongitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double destination_longitude = 17;</code>
     */
    public Builder clearDestinationLongitude() {
      
      destinationLongitude_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 18;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 18;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 18;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 18;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 18;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private double rating_ ;
    /**
     * <code>double rating = 19;</code>
     */
    public double getRating() {
      return rating_;
    }
    /**
     * <code>double rating = 19;</code>
     */
    public Builder setRating(double value) {
      
      rating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rating = 19;</code>
     */
    public Builder clearRating() {
      
      rating_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object vehiclePlateNo_ = "";
    /**
     * <code>string vehicle_plate_no = 20;</code>
     */
    public java.lang.String getVehiclePlateNo() {
      java.lang.Object ref = vehiclePlateNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehiclePlateNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vehicle_plate_no = 20;</code>
     */
    public com.google.protobuf.ByteString
        getVehiclePlateNoBytes() {
      java.lang.Object ref = vehiclePlateNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehiclePlateNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vehicle_plate_no = 20;</code>
     */
    public Builder setVehiclePlateNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vehiclePlateNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_plate_no = 20;</code>
     */
    public Builder clearVehiclePlateNo() {
      
      vehiclePlateNo_ = getDefaultInstance().getVehiclePlateNo();
      onChanged();
      return this;
    }
    /**
     * <code>string vehicle_plate_no = 20;</code>
     */
    public Builder setVehiclePlateNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vehiclePlateNo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:schedule.Reservation)
  }

  // @@protoc_insertion_point(class_scope:schedule.Reservation)
  private static final com.ray.app.grpc.Reservation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ray.app.grpc.Reservation();
  }

  public static com.ray.app.grpc.Reservation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reservation>
      PARSER = new com.google.protobuf.AbstractParser<Reservation>() {
    @java.lang.Override
    public Reservation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Reservation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Reservation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reservation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ray.app.grpc.Reservation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

