// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicle.proto

package com.ray.schedule.grpc;

public interface AvailabilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vehicle.Availability)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_available_for_rent = 1;</code>
   */
  boolean getIsAvailableForRent();

  /**
   * <code>bool is_available_for_ride_hailing = 2;</code>
   */
  boolean getIsAvailableForRideHailing();
}
