// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: email.proto

package com.ray.schedule.grpc;

public interface EmailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:email.Email)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string to = 1;</code>
   */
  java.lang.String getTo();
  /**
   * <code>string to = 1;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string subject = 3;</code>
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3;</code>
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string body = 4;</code>
   */
  java.lang.String getBody();
  /**
   * <code>string body = 4;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
