// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vehicle.proto

package com.ray.schedule.grpc;

/**
 * Protobuf type {@code vehicle.Vehicle}
 */
public  final class Vehicle extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vehicle.Vehicle)
    VehicleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Vehicle.newBuilder() to construct.
  private Vehicle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Vehicle() {
    make_ = "";
    model_ = "";
    year_ = 0;
    color_ = "";
    mileage_ = 0;
    rentPrice_ = 0D;
    engineType_ = "";
    fuelType_ = "";
    transmission_ = "";
    ridePrice_ = 0D;
    fileName_ = "";
    image_ = com.google.protobuf.ByteString.EMPTY;
    ownerName_ = "";
    ownerEmail_ = "";
    isAvailableForRent_ = false;
    isAvailableForRideHailing_ = false;
    id_ = 0;
    plateNo_ = "";
    bodyType_ = "";
    loadImage_ = false;
    status_ = "";
    error_ = "";
    rating_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Vehicle(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            make_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            model_ = s;
            break;
          }
          case 24: {

            year_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            color_ = s;
            break;
          }
          case 40: {

            mileage_ = input.readInt32();
            break;
          }
          case 49: {

            rentPrice_ = input.readDouble();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            engineType_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            fuelType_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            transmission_ = s;
            break;
          }
          case 81: {

            ridePrice_ = input.readDouble();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            fileName_ = s;
            break;
          }
          case 98: {

            image_ = input.readBytes();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerName_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerEmail_ = s;
            break;
          }
          case 120: {

            isAvailableForRent_ = input.readBool();
            break;
          }
          case 128: {

            isAvailableForRideHailing_ = input.readBool();
            break;
          }
          case 138: {
            com.ray.schedule.grpc.VehicleCategory.Builder subBuilder = null;
            if (category_ != null) {
              subBuilder = category_.toBuilder();
            }
            category_ = input.readMessage(com.ray.schedule.grpc.VehicleCategory.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(category_);
              category_ = subBuilder.buildPartial();
            }

            break;
          }
          case 144: {

            id_ = input.readInt32();
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            plateNo_ = s;
            break;
          }
          case 162: {
            java.lang.String s = input.readStringRequireUtf8();

            bodyType_ = s;
            break;
          }
          case 168: {

            loadImage_ = input.readBool();
            break;
          }
          case 186: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 194: {
            java.lang.String s = input.readStringRequireUtf8();

            error_ = s;
            break;
          }
          case 201: {

            rating_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ray.schedule.grpc.VehicleServiceImpl.internal_static_vehicle_Vehicle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ray.schedule.grpc.VehicleServiceImpl.internal_static_vehicle_Vehicle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ray.schedule.grpc.Vehicle.class, com.ray.schedule.grpc.Vehicle.Builder.class);
  }

  public static final int MAKE_FIELD_NUMBER = 1;
  private volatile java.lang.Object make_;
  /**
   * <code>string make = 1;</code>
   */
  public java.lang.String getMake() {
    java.lang.Object ref = make_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      make_ = s;
      return s;
    }
  }
  /**
   * <code>string make = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMakeBytes() {
    java.lang.Object ref = make_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      make_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object model_;
  /**
   * <code>string model = 2;</code>
   */
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>string model = 2;</code>
   */
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YEAR_FIELD_NUMBER = 3;
  private int year_;
  /**
   * <code>int32 year = 3;</code>
   */
  public int getYear() {
    return year_;
  }

  public static final int COLOR_FIELD_NUMBER = 4;
  private volatile java.lang.Object color_;
  /**
   * <code>string color = 4;</code>
   */
  public java.lang.String getColor() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      color_ = s;
      return s;
    }
  }
  /**
   * <code>string color = 4;</code>
   */
  public com.google.protobuf.ByteString
      getColorBytes() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      color_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MILEAGE_FIELD_NUMBER = 5;
  private int mileage_;
  /**
   * <code>int32 mileage = 5;</code>
   */
  public int getMileage() {
    return mileage_;
  }

  public static final int RENT_PRICE_FIELD_NUMBER = 6;
  private double rentPrice_;
  /**
   * <code>double rent_price = 6;</code>
   */
  public double getRentPrice() {
    return rentPrice_;
  }

  public static final int ENGINE_TYPE_FIELD_NUMBER = 7;
  private volatile java.lang.Object engineType_;
  /**
   * <code>string engine_type = 7;</code>
   */
  public java.lang.String getEngineType() {
    java.lang.Object ref = engineType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engineType_ = s;
      return s;
    }
  }
  /**
   * <code>string engine_type = 7;</code>
   */
  public com.google.protobuf.ByteString
      getEngineTypeBytes() {
    java.lang.Object ref = engineType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engineType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUEL_TYPE_FIELD_NUMBER = 8;
  private volatile java.lang.Object fuelType_;
  /**
   * <code>string fuel_type = 8;</code>
   */
  public java.lang.String getFuelType() {
    java.lang.Object ref = fuelType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fuelType_ = s;
      return s;
    }
  }
  /**
   * <code>string fuel_type = 8;</code>
   */
  public com.google.protobuf.ByteString
      getFuelTypeBytes() {
    java.lang.Object ref = fuelType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fuelType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSMISSION_FIELD_NUMBER = 9;
  private volatile java.lang.Object transmission_;
  /**
   * <code>string transmission = 9;</code>
   */
  public java.lang.String getTransmission() {
    java.lang.Object ref = transmission_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transmission_ = s;
      return s;
    }
  }
  /**
   * <code>string transmission = 9;</code>
   */
  public com.google.protobuf.ByteString
      getTransmissionBytes() {
    java.lang.Object ref = transmission_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transmission_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RIDE_PRICE_FIELD_NUMBER = 10;
  private double ridePrice_;
  /**
   * <code>double ride_price = 10;</code>
   */
  public double getRidePrice() {
    return ridePrice_;
  }

  public static final int FILENAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object fileName_;
  /**
   * <code>string fileName = 11;</code>
   */
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 11;</code>
   */
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString image_;
  /**
   * <code>bytes image = 12;</code>
   */
  public com.google.protobuf.ByteString getImage() {
    return image_;
  }

  public static final int OWNER_NAME_FIELD_NUMBER = 13;
  private volatile java.lang.Object ownerName_;
  /**
   * <code>string owner_name = 13;</code>
   */
  public java.lang.String getOwnerName() {
    java.lang.Object ref = ownerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerName_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_name = 13;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerNameBytes() {
    java.lang.Object ref = ownerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_EMAIL_FIELD_NUMBER = 14;
  private volatile java.lang.Object ownerEmail_;
  /**
   * <code>string owner_email = 14;</code>
   */
  public java.lang.String getOwnerEmail() {
    java.lang.Object ref = ownerEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_email = 14;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerEmailBytes() {
    java.lang.Object ref = ownerEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_AVAILABLE_FOR_RENT_FIELD_NUMBER = 15;
  private boolean isAvailableForRent_;
  /**
   * <code>bool is_available_for_rent = 15;</code>
   */
  public boolean getIsAvailableForRent() {
    return isAvailableForRent_;
  }

  public static final int IS_AVAILABLE_FOR_RIDE_HAILING_FIELD_NUMBER = 16;
  private boolean isAvailableForRideHailing_;
  /**
   * <code>bool is_available_for_ride_hailing = 16;</code>
   */
  public boolean getIsAvailableForRideHailing() {
    return isAvailableForRideHailing_;
  }

  public static final int CATEGORY_FIELD_NUMBER = 17;
  private com.ray.schedule.grpc.VehicleCategory category_;
  /**
   * <code>.vehicle.VehicleCategory category = 17;</code>
   */
  public boolean hasCategory() {
    return category_ != null;
  }
  /**
   * <code>.vehicle.VehicleCategory category = 17;</code>
   */
  public com.ray.schedule.grpc.VehicleCategory getCategory() {
    return category_ == null ? com.ray.schedule.grpc.VehicleCategory.getDefaultInstance() : category_;
  }
  /**
   * <code>.vehicle.VehicleCategory category = 17;</code>
   */
  public com.ray.schedule.grpc.VehicleCategoryOrBuilder getCategoryOrBuilder() {
    return getCategory();
  }

  public static final int ID_FIELD_NUMBER = 18;
  private int id_;
  /**
   * <code>int32 id = 18;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int PLATE_NO_FIELD_NUMBER = 19;
  private volatile java.lang.Object plateNo_;
  /**
   * <code>string plate_no = 19;</code>
   */
  public java.lang.String getPlateNo() {
    java.lang.Object ref = plateNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      plateNo_ = s;
      return s;
    }
  }
  /**
   * <code>string plate_no = 19;</code>
   */
  public com.google.protobuf.ByteString
      getPlateNoBytes() {
    java.lang.Object ref = plateNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      plateNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_TYPE_FIELD_NUMBER = 20;
  private volatile java.lang.Object bodyType_;
  /**
   * <code>string body_type = 20;</code>
   */
  public java.lang.String getBodyType() {
    java.lang.Object ref = bodyType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bodyType_ = s;
      return s;
    }
  }
  /**
   * <code>string body_type = 20;</code>
   */
  public com.google.protobuf.ByteString
      getBodyTypeBytes() {
    java.lang.Object ref = bodyType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bodyType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOADIMAGE_FIELD_NUMBER = 21;
  private boolean loadImage_;
  /**
   * <code>bool loadImage = 21;</code>
   */
  public boolean getLoadImage() {
    return loadImage_;
  }

  public static final int STATUS_FIELD_NUMBER = 23;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 23;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 23;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 24;
  private volatile java.lang.Object error_;
  /**
   * <code>string error = 24;</code>
   */
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 24;</code>
   */
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATING_FIELD_NUMBER = 25;
  private double rating_;
  /**
   * <code>double rating = 25;</code>
   */
  public double getRating() {
    return rating_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMakeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, make_);
    }
    if (!getModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, model_);
    }
    if (year_ != 0) {
      output.writeInt32(3, year_);
    }
    if (!getColorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, color_);
    }
    if (mileage_ != 0) {
      output.writeInt32(5, mileage_);
    }
    if (rentPrice_ != 0D) {
      output.writeDouble(6, rentPrice_);
    }
    if (!getEngineTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, engineType_);
    }
    if (!getFuelTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fuelType_);
    }
    if (!getTransmissionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, transmission_);
    }
    if (ridePrice_ != 0D) {
      output.writeDouble(10, ridePrice_);
    }
    if (!getFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, fileName_);
    }
    if (!image_.isEmpty()) {
      output.writeBytes(12, image_);
    }
    if (!getOwnerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, ownerName_);
    }
    if (!getOwnerEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, ownerEmail_);
    }
    if (isAvailableForRent_ != false) {
      output.writeBool(15, isAvailableForRent_);
    }
    if (isAvailableForRideHailing_ != false) {
      output.writeBool(16, isAvailableForRideHailing_);
    }
    if (category_ != null) {
      output.writeMessage(17, getCategory());
    }
    if (id_ != 0) {
      output.writeInt32(18, id_);
    }
    if (!getPlateNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, plateNo_);
    }
    if (!getBodyTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, bodyType_);
    }
    if (loadImage_ != false) {
      output.writeBool(21, loadImage_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 23, status_);
    }
    if (!getErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 24, error_);
    }
    if (rating_ != 0D) {
      output.writeDouble(25, rating_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMakeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, make_);
    }
    if (!getModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, model_);
    }
    if (year_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, year_);
    }
    if (!getColorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, color_);
    }
    if (mileage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, mileage_);
    }
    if (rentPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, rentPrice_);
    }
    if (!getEngineTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, engineType_);
    }
    if (!getFuelTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fuelType_);
    }
    if (!getTransmissionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, transmission_);
    }
    if (ridePrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, ridePrice_);
    }
    if (!getFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, fileName_);
    }
    if (!image_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, image_);
    }
    if (!getOwnerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, ownerName_);
    }
    if (!getOwnerEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, ownerEmail_);
    }
    if (isAvailableForRent_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(15, isAvailableForRent_);
    }
    if (isAvailableForRideHailing_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, isAvailableForRideHailing_);
    }
    if (category_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getCategory());
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(18, id_);
    }
    if (!getPlateNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, plateNo_);
    }
    if (!getBodyTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, bodyType_);
    }
    if (loadImage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(21, loadImage_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(23, status_);
    }
    if (!getErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(24, error_);
    }
    if (rating_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(25, rating_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ray.schedule.grpc.Vehicle)) {
      return super.equals(obj);
    }
    com.ray.schedule.grpc.Vehicle other = (com.ray.schedule.grpc.Vehicle) obj;

    boolean result = true;
    result = result && getMake()
        .equals(other.getMake());
    result = result && getModel()
        .equals(other.getModel());
    result = result && (getYear()
        == other.getYear());
    result = result && getColor()
        .equals(other.getColor());
    result = result && (getMileage()
        == other.getMileage());
    result = result && (
        java.lang.Double.doubleToLongBits(getRentPrice())
        == java.lang.Double.doubleToLongBits(
            other.getRentPrice()));
    result = result && getEngineType()
        .equals(other.getEngineType());
    result = result && getFuelType()
        .equals(other.getFuelType());
    result = result && getTransmission()
        .equals(other.getTransmission());
    result = result && (
        java.lang.Double.doubleToLongBits(getRidePrice())
        == java.lang.Double.doubleToLongBits(
            other.getRidePrice()));
    result = result && getFileName()
        .equals(other.getFileName());
    result = result && getImage()
        .equals(other.getImage());
    result = result && getOwnerName()
        .equals(other.getOwnerName());
    result = result && getOwnerEmail()
        .equals(other.getOwnerEmail());
    result = result && (getIsAvailableForRent()
        == other.getIsAvailableForRent());
    result = result && (getIsAvailableForRideHailing()
        == other.getIsAvailableForRideHailing());
    result = result && (hasCategory() == other.hasCategory());
    if (hasCategory()) {
      result = result && getCategory()
          .equals(other.getCategory());
    }
    result = result && (getId()
        == other.getId());
    result = result && getPlateNo()
        .equals(other.getPlateNo());
    result = result && getBodyType()
        .equals(other.getBodyType());
    result = result && (getLoadImage()
        == other.getLoadImage());
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && getError()
        .equals(other.getError());
    result = result && (
        java.lang.Double.doubleToLongBits(getRating())
        == java.lang.Double.doubleToLongBits(
            other.getRating()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAKE_FIELD_NUMBER;
    hash = (53 * hash) + getMake().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getYear();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor().hashCode();
    hash = (37 * hash) + MILEAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMileage();
    hash = (37 * hash) + RENT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRentPrice()));
    hash = (37 * hash) + ENGINE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEngineType().hashCode();
    hash = (37 * hash) + FUEL_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFuelType().hashCode();
    hash = (37 * hash) + TRANSMISSION_FIELD_NUMBER;
    hash = (53 * hash) + getTransmission().hashCode();
    hash = (37 * hash) + RIDE_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRidePrice()));
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getImage().hashCode();
    hash = (37 * hash) + OWNER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerName().hashCode();
    hash = (37 * hash) + OWNER_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerEmail().hashCode();
    hash = (37 * hash) + IS_AVAILABLE_FOR_RENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAvailableForRent());
    hash = (37 * hash) + IS_AVAILABLE_FOR_RIDE_HAILING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAvailableForRideHailing());
    if (hasCategory()) {
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + PLATE_NO_FIELD_NUMBER;
    hash = (53 * hash) + getPlateNo().hashCode();
    hash = (37 * hash) + BODY_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getBodyType().hashCode();
    hash = (37 * hash) + LOADIMAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLoadImage());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRating()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ray.schedule.grpc.Vehicle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ray.schedule.grpc.Vehicle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ray.schedule.grpc.Vehicle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ray.schedule.grpc.Vehicle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ray.schedule.grpc.Vehicle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vehicle.Vehicle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vehicle.Vehicle)
      com.ray.schedule.grpc.VehicleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ray.schedule.grpc.VehicleServiceImpl.internal_static_vehicle_Vehicle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ray.schedule.grpc.VehicleServiceImpl.internal_static_vehicle_Vehicle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ray.schedule.grpc.Vehicle.class, com.ray.schedule.grpc.Vehicle.Builder.class);
    }

    // Construct using com.ray.schedule.grpc.Vehicle.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      make_ = "";

      model_ = "";

      year_ = 0;

      color_ = "";

      mileage_ = 0;

      rentPrice_ = 0D;

      engineType_ = "";

      fuelType_ = "";

      transmission_ = "";

      ridePrice_ = 0D;

      fileName_ = "";

      image_ = com.google.protobuf.ByteString.EMPTY;

      ownerName_ = "";

      ownerEmail_ = "";

      isAvailableForRent_ = false;

      isAvailableForRideHailing_ = false;

      if (categoryBuilder_ == null) {
        category_ = null;
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }
      id_ = 0;

      plateNo_ = "";

      bodyType_ = "";

      loadImage_ = false;

      status_ = "";

      error_ = "";

      rating_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ray.schedule.grpc.VehicleServiceImpl.internal_static_vehicle_Vehicle_descriptor;
    }

    @java.lang.Override
    public com.ray.schedule.grpc.Vehicle getDefaultInstanceForType() {
      return com.ray.schedule.grpc.Vehicle.getDefaultInstance();
    }

    @java.lang.Override
    public com.ray.schedule.grpc.Vehicle build() {
      com.ray.schedule.grpc.Vehicle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ray.schedule.grpc.Vehicle buildPartial() {
      com.ray.schedule.grpc.Vehicle result = new com.ray.schedule.grpc.Vehicle(this);
      result.make_ = make_;
      result.model_ = model_;
      result.year_ = year_;
      result.color_ = color_;
      result.mileage_ = mileage_;
      result.rentPrice_ = rentPrice_;
      result.engineType_ = engineType_;
      result.fuelType_ = fuelType_;
      result.transmission_ = transmission_;
      result.ridePrice_ = ridePrice_;
      result.fileName_ = fileName_;
      result.image_ = image_;
      result.ownerName_ = ownerName_;
      result.ownerEmail_ = ownerEmail_;
      result.isAvailableForRent_ = isAvailableForRent_;
      result.isAvailableForRideHailing_ = isAvailableForRideHailing_;
      if (categoryBuilder_ == null) {
        result.category_ = category_;
      } else {
        result.category_ = categoryBuilder_.build();
      }
      result.id_ = id_;
      result.plateNo_ = plateNo_;
      result.bodyType_ = bodyType_;
      result.loadImage_ = loadImage_;
      result.status_ = status_;
      result.error_ = error_;
      result.rating_ = rating_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ray.schedule.grpc.Vehicle) {
        return mergeFrom((com.ray.schedule.grpc.Vehicle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ray.schedule.grpc.Vehicle other) {
      if (other == com.ray.schedule.grpc.Vehicle.getDefaultInstance()) return this;
      if (!other.getMake().isEmpty()) {
        make_ = other.make_;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (other.getYear() != 0) {
        setYear(other.getYear());
      }
      if (!other.getColor().isEmpty()) {
        color_ = other.color_;
        onChanged();
      }
      if (other.getMileage() != 0) {
        setMileage(other.getMileage());
      }
      if (other.getRentPrice() != 0D) {
        setRentPrice(other.getRentPrice());
      }
      if (!other.getEngineType().isEmpty()) {
        engineType_ = other.engineType_;
        onChanged();
      }
      if (!other.getFuelType().isEmpty()) {
        fuelType_ = other.fuelType_;
        onChanged();
      }
      if (!other.getTransmission().isEmpty()) {
        transmission_ = other.transmission_;
        onChanged();
      }
      if (other.getRidePrice() != 0D) {
        setRidePrice(other.getRidePrice());
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      if (other.getImage() != com.google.protobuf.ByteString.EMPTY) {
        setImage(other.getImage());
      }
      if (!other.getOwnerName().isEmpty()) {
        ownerName_ = other.ownerName_;
        onChanged();
      }
      if (!other.getOwnerEmail().isEmpty()) {
        ownerEmail_ = other.ownerEmail_;
        onChanged();
      }
      if (other.getIsAvailableForRent() != false) {
        setIsAvailableForRent(other.getIsAvailableForRent());
      }
      if (other.getIsAvailableForRideHailing() != false) {
        setIsAvailableForRideHailing(other.getIsAvailableForRideHailing());
      }
      if (other.hasCategory()) {
        mergeCategory(other.getCategory());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getPlateNo().isEmpty()) {
        plateNo_ = other.plateNo_;
        onChanged();
      }
      if (!other.getBodyType().isEmpty()) {
        bodyType_ = other.bodyType_;
        onChanged();
      }
      if (other.getLoadImage() != false) {
        setLoadImage(other.getLoadImage());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        onChanged();
      }
      if (other.getRating() != 0D) {
        setRating(other.getRating());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ray.schedule.grpc.Vehicle parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ray.schedule.grpc.Vehicle) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object make_ = "";
    /**
     * <code>string make = 1;</code>
     */
    public java.lang.String getMake() {
      java.lang.Object ref = make_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        make_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string make = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMakeBytes() {
      java.lang.Object ref = make_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        make_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string make = 1;</code>
     */
    public Builder setMake(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      make_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string make = 1;</code>
     */
    public Builder clearMake() {
      
      make_ = getDefaultInstance().getMake();
      onChanged();
      return this;
    }
    /**
     * <code>string make = 1;</code>
     */
    public Builder setMakeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      make_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <code>string model = 2;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model = 2;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model = 2;</code>
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2;</code>
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2;</code>
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private int year_ ;
    /**
     * <code>int32 year = 3;</code>
     */
    public int getYear() {
      return year_;
    }
    /**
     * <code>int32 year = 3;</code>
     */
    public Builder setYear(int value) {
      
      year_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 year = 3;</code>
     */
    public Builder clearYear() {
      
      year_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object color_ = "";
    /**
     * <code>string color = 4;</code>
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string color = 4;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string color = 4;</code>
     */
    public Builder setColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string color = 4;</code>
     */
    public Builder clearColor() {
      
      color_ = getDefaultInstance().getColor();
      onChanged();
      return this;
    }
    /**
     * <code>string color = 4;</code>
     */
    public Builder setColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      color_ = value;
      onChanged();
      return this;
    }

    private int mileage_ ;
    /**
     * <code>int32 mileage = 5;</code>
     */
    public int getMileage() {
      return mileage_;
    }
    /**
     * <code>int32 mileage = 5;</code>
     */
    public Builder setMileage(int value) {
      
      mileage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mileage = 5;</code>
     */
    public Builder clearMileage() {
      
      mileage_ = 0;
      onChanged();
      return this;
    }

    private double rentPrice_ ;
    /**
     * <code>double rent_price = 6;</code>
     */
    public double getRentPrice() {
      return rentPrice_;
    }
    /**
     * <code>double rent_price = 6;</code>
     */
    public Builder setRentPrice(double value) {
      
      rentPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rent_price = 6;</code>
     */
    public Builder clearRentPrice() {
      
      rentPrice_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object engineType_ = "";
    /**
     * <code>string engine_type = 7;</code>
     */
    public java.lang.String getEngineType() {
      java.lang.Object ref = engineType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string engine_type = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEngineTypeBytes() {
      java.lang.Object ref = engineType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string engine_type = 7;</code>
     */
    public Builder setEngineType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      engineType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string engine_type = 7;</code>
     */
    public Builder clearEngineType() {
      
      engineType_ = getDefaultInstance().getEngineType();
      onChanged();
      return this;
    }
    /**
     * <code>string engine_type = 7;</code>
     */
    public Builder setEngineTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      engineType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fuelType_ = "";
    /**
     * <code>string fuel_type = 8;</code>
     */
    public java.lang.String getFuelType() {
      java.lang.Object ref = fuelType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fuelType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fuel_type = 8;</code>
     */
    public com.google.protobuf.ByteString
        getFuelTypeBytes() {
      java.lang.Object ref = fuelType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fuelType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fuel_type = 8;</code>
     */
    public Builder setFuelType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fuelType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fuel_type = 8;</code>
     */
    public Builder clearFuelType() {
      
      fuelType_ = getDefaultInstance().getFuelType();
      onChanged();
      return this;
    }
    /**
     * <code>string fuel_type = 8;</code>
     */
    public Builder setFuelTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fuelType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transmission_ = "";
    /**
     * <code>string transmission = 9;</code>
     */
    public java.lang.String getTransmission() {
      java.lang.Object ref = transmission_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transmission_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transmission = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTransmissionBytes() {
      java.lang.Object ref = transmission_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transmission_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transmission = 9;</code>
     */
    public Builder setTransmission(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transmission_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transmission = 9;</code>
     */
    public Builder clearTransmission() {
      
      transmission_ = getDefaultInstance().getTransmission();
      onChanged();
      return this;
    }
    /**
     * <code>string transmission = 9;</code>
     */
    public Builder setTransmissionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transmission_ = value;
      onChanged();
      return this;
    }

    private double ridePrice_ ;
    /**
     * <code>double ride_price = 10;</code>
     */
    public double getRidePrice() {
      return ridePrice_;
    }
    /**
     * <code>double ride_price = 10;</code>
     */
    public Builder setRidePrice(double value) {
      
      ridePrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double ride_price = 10;</code>
     */
    public Builder clearRidePrice() {
      
      ridePrice_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 11;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 11;</code>
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 11;</code>
     */
    public Builder clearFileName() {
      
      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 11;</code>
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes image = 12;</code>
     */
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }
    /**
     * <code>bytes image = 12;</code>
     */
    public Builder setImage(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      image_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes image = 12;</code>
     */
    public Builder clearImage() {
      
      image_ = getDefaultInstance().getImage();
      onChanged();
      return this;
    }

    private java.lang.Object ownerName_ = "";
    /**
     * <code>string owner_name = 13;</code>
     */
    public java.lang.String getOwnerName() {
      java.lang.Object ref = ownerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner_name = 13;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerNameBytes() {
      java.lang.Object ref = ownerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_name = 13;</code>
     */
    public Builder setOwnerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_name = 13;</code>
     */
    public Builder clearOwnerName() {
      
      ownerName_ = getDefaultInstance().getOwnerName();
      onChanged();
      return this;
    }
    /**
     * <code>string owner_name = 13;</code>
     */
    public Builder setOwnerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ownerEmail_ = "";
    /**
     * <code>string owner_email = 14;</code>
     */
    public java.lang.String getOwnerEmail() {
      java.lang.Object ref = ownerEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner_email = 14;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerEmailBytes() {
      java.lang.Object ref = ownerEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_email = 14;</code>
     */
    public Builder setOwnerEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_email = 14;</code>
     */
    public Builder clearOwnerEmail() {
      
      ownerEmail_ = getDefaultInstance().getOwnerEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string owner_email = 14;</code>
     */
    public Builder setOwnerEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerEmail_ = value;
      onChanged();
      return this;
    }

    private boolean isAvailableForRent_ ;
    /**
     * <code>bool is_available_for_rent = 15;</code>
     */
    public boolean getIsAvailableForRent() {
      return isAvailableForRent_;
    }
    /**
     * <code>bool is_available_for_rent = 15;</code>
     */
    public Builder setIsAvailableForRent(boolean value) {
      
      isAvailableForRent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_available_for_rent = 15;</code>
     */
    public Builder clearIsAvailableForRent() {
      
      isAvailableForRent_ = false;
      onChanged();
      return this;
    }

    private boolean isAvailableForRideHailing_ ;
    /**
     * <code>bool is_available_for_ride_hailing = 16;</code>
     */
    public boolean getIsAvailableForRideHailing() {
      return isAvailableForRideHailing_;
    }
    /**
     * <code>bool is_available_for_ride_hailing = 16;</code>
     */
    public Builder setIsAvailableForRideHailing(boolean value) {
      
      isAvailableForRideHailing_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_available_for_ride_hailing = 16;</code>
     */
    public Builder clearIsAvailableForRideHailing() {
      
      isAvailableForRideHailing_ = false;
      onChanged();
      return this;
    }

    private com.ray.schedule.grpc.VehicleCategory category_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.schedule.grpc.VehicleCategory, com.ray.schedule.grpc.VehicleCategory.Builder, com.ray.schedule.grpc.VehicleCategoryOrBuilder> categoryBuilder_;
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public boolean hasCategory() {
      return categoryBuilder_ != null || category_ != null;
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public com.ray.schedule.grpc.VehicleCategory getCategory() {
      if (categoryBuilder_ == null) {
        return category_ == null ? com.ray.schedule.grpc.VehicleCategory.getDefaultInstance() : category_;
      } else {
        return categoryBuilder_.getMessage();
      }
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public Builder setCategory(com.ray.schedule.grpc.VehicleCategory value) {
      if (categoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        category_ = value;
        onChanged();
      } else {
        categoryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public Builder setCategory(
        com.ray.schedule.grpc.VehicleCategory.Builder builderForValue) {
      if (categoryBuilder_ == null) {
        category_ = builderForValue.build();
        onChanged();
      } else {
        categoryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public Builder mergeCategory(com.ray.schedule.grpc.VehicleCategory value) {
      if (categoryBuilder_ == null) {
        if (category_ != null) {
          category_ =
            com.ray.schedule.grpc.VehicleCategory.newBuilder(category_).mergeFrom(value).buildPartial();
        } else {
          category_ = value;
        }
        onChanged();
      } else {
        categoryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public Builder clearCategory() {
      if (categoryBuilder_ == null) {
        category_ = null;
        onChanged();
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public com.ray.schedule.grpc.VehicleCategory.Builder getCategoryBuilder() {
      
      onChanged();
      return getCategoryFieldBuilder().getBuilder();
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    public com.ray.schedule.grpc.VehicleCategoryOrBuilder getCategoryOrBuilder() {
      if (categoryBuilder_ != null) {
        return categoryBuilder_.getMessageOrBuilder();
      } else {
        return category_ == null ?
            com.ray.schedule.grpc.VehicleCategory.getDefaultInstance() : category_;
      }
    }
    /**
     * <code>.vehicle.VehicleCategory category = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ray.schedule.grpc.VehicleCategory, com.ray.schedule.grpc.VehicleCategory.Builder, com.ray.schedule.grpc.VehicleCategoryOrBuilder> 
        getCategoryFieldBuilder() {
      if (categoryBuilder_ == null) {
        categoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ray.schedule.grpc.VehicleCategory, com.ray.schedule.grpc.VehicleCategory.Builder, com.ray.schedule.grpc.VehicleCategoryOrBuilder>(
                getCategory(),
                getParentForChildren(),
                isClean());
        category_ = null;
      }
      return categoryBuilder_;
    }

    private int id_ ;
    /**
     * <code>int32 id = 18;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 18;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 18;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object plateNo_ = "";
    /**
     * <code>string plate_no = 19;</code>
     */
    public java.lang.String getPlateNo() {
      java.lang.Object ref = plateNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plateNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plate_no = 19;</code>
     */
    public com.google.protobuf.ByteString
        getPlateNoBytes() {
      java.lang.Object ref = plateNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plateNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plate_no = 19;</code>
     */
    public Builder setPlateNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      plateNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string plate_no = 19;</code>
     */
    public Builder clearPlateNo() {
      
      plateNo_ = getDefaultInstance().getPlateNo();
      onChanged();
      return this;
    }
    /**
     * <code>string plate_no = 19;</code>
     */
    public Builder setPlateNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      plateNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bodyType_ = "";
    /**
     * <code>string body_type = 20;</code>
     */
    public java.lang.String getBodyType() {
      java.lang.Object ref = bodyType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bodyType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body_type = 20;</code>
     */
    public com.google.protobuf.ByteString
        getBodyTypeBytes() {
      java.lang.Object ref = bodyType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bodyType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body_type = 20;</code>
     */
    public Builder setBodyType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bodyType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string body_type = 20;</code>
     */
    public Builder clearBodyType() {
      
      bodyType_ = getDefaultInstance().getBodyType();
      onChanged();
      return this;
    }
    /**
     * <code>string body_type = 20;</code>
     */
    public Builder setBodyTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bodyType_ = value;
      onChanged();
      return this;
    }

    private boolean loadImage_ ;
    /**
     * <code>bool loadImage = 21;</code>
     */
    public boolean getLoadImage() {
      return loadImage_;
    }
    /**
     * <code>bool loadImage = 21;</code>
     */
    public Builder setLoadImage(boolean value) {
      
      loadImage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool loadImage = 21;</code>
     */
    public Builder clearLoadImage() {
      
      loadImage_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 23;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 23;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 23;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 23;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 23;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 24;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 24;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 24;</code>
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 24;</code>
     */
    public Builder clearError() {
      
      error_ = getDefaultInstance().getError();
      onChanged();
      return this;
    }
    /**
     * <code>string error = 24;</code>
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      error_ = value;
      onChanged();
      return this;
    }

    private double rating_ ;
    /**
     * <code>double rating = 25;</code>
     */
    public double getRating() {
      return rating_;
    }
    /**
     * <code>double rating = 25;</code>
     */
    public Builder setRating(double value) {
      
      rating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rating = 25;</code>
     */
    public Builder clearRating() {
      
      rating_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vehicle.Vehicle)
  }

  // @@protoc_insertion_point(class_scope:vehicle.Vehicle)
  private static final com.ray.schedule.grpc.Vehicle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ray.schedule.grpc.Vehicle();
  }

  public static com.ray.schedule.grpc.Vehicle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Vehicle>
      PARSER = new com.google.protobuf.AbstractParser<Vehicle>() {
    @java.lang.Override
    public Vehicle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Vehicle(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Vehicle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Vehicle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ray.schedule.grpc.Vehicle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

